name: Check SemVer

on:
  push:
    branches: ['main']
    tags:
      - '*'
  workflow_dispatch:

permissions: {}

jobs:
  check-semver:
    permissions:
      contents: write

    concurrency:
      group: '${{ github.workflow }}'
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - uses: jessehouwing/actions-semver-checker@5655d277505de61cbd7e7a86cb2bcd7e95807ea0 # v2.0.7
        with:
          check-minor-version: error
          check-release-immutability: true
          ignore-preview-releases: true
          check-releases: error
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-fix: true
